PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, emailVerified INTEGER NOT NULL DEFAULT 0, image TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, username TEXT NOT NULL UNIQUE, displayUsername TEXT, role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('admin','member')), bio TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS session (id TEXT PRIMARY KEY, expiresAt INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, ipAddress TEXT, userAgent TEXT, userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS session_user ON session(userId);
CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY, accountId TEXT NOT NULL, providerId TEXT NOT NULL, userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, accessToken TEXT, refreshToken TEXT, idToken TEXT, accessTokenExpiresAt INTEGER, refreshTokenExpiresAt INTEGER, scope TEXT, password TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, UNIQUE(providerId,accountId));
CREATE TABLE IF NOT EXISTS verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expiresAt INTEGER NOT NULL, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS verification_identifier ON verification(identifier);
CREATE TABLE IF NOT EXISTS invitations (id TEXT PRIMARY KEY, tokenHash TEXT NOT NULL UNIQUE, createdBy TEXT NOT NULL REFERENCES user(id), createdAt INTEGER NOT NULL, expiresAt INTEGER NOT NULL, consumedBy TEXT REFERENCES user(id), consumedAt INTEGER);
CREATE TABLE IF NOT EXISTS circuits (id TEXT PRIMARY KEY, ownerId TEXT NOT NULL REFERENCES user(id), title TEXT NOT NULL, document TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, writeId TEXT NOT NULL DEFAULT '', forkedFrom TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS circuits_owner ON circuits(ownerId,updatedAt DESC);
CREATE TABLE IF NOT EXISTS publications (id TEXT PRIMARY KEY, circuitId TEXT NOT NULL, ownerId TEXT NOT NULL REFERENCES user(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', document TEXT NOT NULL, sourceRevision INTEGER NOT NULL, createdAt INTEGER NOT NULL, UNIQUE(circuitId,sourceRevision));
CREATE INDEX IF NOT EXISTS publications_created ON publications(createdAt DESC);
CREATE TABLE IF NOT EXISTS reactions (userId TEXT NOT NULL REFERENCES user(id), publicationId TEXT NOT NULL REFERENCES publications(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('like','favorite')), createdAt INTEGER NOT NULL, PRIMARY KEY(userId,publicationId,kind));
CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, ownerId TEXT NOT NULL REFERENCES user(id), objectKey TEXT NOT NULL UNIQUE, name TEXT NOT NULL, type TEXT NOT NULL, size INTEGER NOT NULL, createdAt INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS circuit_media (circuitId TEXT NOT NULL REFERENCES circuits(id) ON DELETE CASCADE, mediaId TEXT NOT NULL REFERENCES media(id), PRIMARY KEY(circuitId,mediaId));
CREATE TABLE IF NOT EXISTS publication_media (publicationId TEXT NOT NULL REFERENCES publications(id) ON DELETE CASCADE, mediaId TEXT NOT NULL REFERENCES media(id), PRIMARY KEY(publicationId,mediaId));
CREATE TABLE IF NOT EXISTS assessments (id TEXT PRIMARY KEY, userId TEXT NOT NULL REFERENCES user(id), lessonId TEXT NOT NULL, documentHash TEXT NOT NULL, result TEXT NOT NULL, createdAt INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS assessments_user ON assessments(userId,createdAt DESC);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expiresAt INTEGER NOT NULL);
