/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: 6ffa4765d4b13ca01d8070493f83e1c4)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_SECRET: string;
	BOOTSTRAP_SECRET: string;
	APP_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BOOTSTRAP_SECRET" | "APP_ORIGIN">> {}
}
