import { useState } from 'react';
import CourseLibrary from './CourseLibrary';
import DrawingViewer from './DrawingViewer';
import Modal from './Modal';
import type { Project } from './TrainingProjects';
import { STATIC_DEMO } from './api';
import { ChevronLeft, ChevronRight, Search, X } from 'lucide-react';
import ReferenceVideoPlayer from './reference-video/ReferenceVideoPlayer';
import { referenceVideoForDiagram } from './reference-video/catalog';
import { REFERENCE_DRAWINGS, referenceDrawingImageUrl } from './core/reference-drawings';

// Only these four existing examples carry course assessment; a reference ID does not imply a lesson.
const courses: Record<number,string> = {13:'motor-jog',14:'motor-self-hold',12:'lighting-two-way',11:'lighting-single'};
const drawings=REFERENCE_DRAWINGS.map(drawing=>({...drawing,lesson:courses[drawing.id],src:referenceDrawingImageUrl(drawing.id,import.meta.env.BASE_URL||'/')!}));
export default function ReferenceDrawings({ onPractice, onProjectPractice, onReferencePractice }: { onReferencePractice:(id:number)=>void; onPractice: (lessonId:string, wired:boolean)=>void; onProjectPractice:(project:Project,wired:boolean)=>void }) {
  const [category,setCategory]=useState(STATIC_DEMO?'industrial':'courses'); const [level,setLevel]=useState('all'); const [query,setQuery]=useState(''); const [page,setPage]=useState(1); const [preview,setPreview]=useState<(typeof drawings)[number]|null>(null);
  const [previewTab,setPreviewTab]=useState<'schematic'|'video'>('schematic');
  const inCategory=drawings.filter(d=>d.category===category); const found=inCategory.filter(d=>(level==='all'||d.level===level)&&d.title.includes(query)); const pages=Math.max(1,Math.ceil(found.length/8));
  return <main className="dt-reference-library"><div className="dt-reference-category" role="tablist" aria-label="图纸分类">{[...(!STATIC_DEMO?[['courses','课程图纸',10]]:[]),['industrial','工业电路图纸',16],['lighting','家庭电路图纸',2]].map(([id,label,count])=><button role="tab" aria-selected={category===id} className={category===id?'active':''} key={id} onClick={()=>{setCategory(String(id));setPage(1);setLevel('all');}}>{label}({count})</button>)}</div>{category==='courses'?<CourseLibrary onPractice={onProjectPractice}/>:<><div className="dt-reference-filter"><div role="tablist" aria-label="图纸难度">{[['all','全部图纸'],['basic','初级图纸'],['intermediate','中级图纸'],['advanced','高级图纸']].map(([id,label])=><button role="tab" aria-selected={level===id} className={level===id?'active':''} key={id} onClick={()=>{setLevel(id);setPage(1);}}>{label}({inCategory.filter(d=>id==='all'||d.level===id).length})</button>)}</div><label className="dt-search"><Search size={16}/><input placeholder="请输入图纸名称" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label></div><div className="dt-reference-grid">{found.slice((page-1)*8,page*8).map(d=><button className="dt-reference-card" key={d.id} onClick={()=>{setPreviewTab('schematic');setPreview(d);}}><img src={d.src} alt={d.title}/><span>{d.title}</span></button>)}</div>{!found.length&&<div className="dt-empty">没有找到匹配图纸</div>}<nav className="dt-pagination" aria-label="图纸分页"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={14}/>上一页</button>{Array.from({length:pages},(_,i)=><button key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>下一页<ChevronRight size={14}/></button></nav></>}
    {preview&&<Modal className="dt-modal dt-reference-modal" title={preview.title} onClose={()=>setPreview(null)}><header><h2>{preview.title}</h2><button aria-label="关闭" onClick={()=>setPreview(null)}><X size={20}/></button></header><div className="dt-reference-preview-tabs" role="tablist" aria-label="参考图纸内容"><button role="tab" aria-selected={previewTab==='schematic'} className={previewTab==='schematic'?'active':''} onClick={()=>setPreviewTab('schematic')}>接线图</button><button role="tab" aria-selected={previewTab==='video'} className={previewTab==='video'?'active':''} onClick={()=>setPreviewTab('video')}>教学视频</button></div>{previewTab==='schematic'?<DrawingViewer key={preview.id} src={preview.src} title={preview.title}/>:<ReferenceVideoPlayer video={referenceVideoForDiagram(preview.id)}/>}{preview.id===11&&<p className="dt-hint">原图包含电度表和多个负载。下方示范只覆盖单控照明。</p>}{preview.id===13&&<p className="dt-hint">按原站图理解点动逻辑；点动示范另检查保护接地与过载保护。</p>}{!preview.lesson&&<p className="dt-hint">可按此参考图接线；此图尚未绑定课程判定。</p>}<div className="dt-modal-actions">{preview.lesson&&<button onClick={()=>{onPractice(preview.lesson,true);setPreview(null);}}>查看示范接线</button>}<button className="dt-primary" onClick={()=>{onReferencePractice(preview.id);setPreview(null);}}>进入电路配置</button></div></Modal>}
  </main>;
}
