import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const fixture=JSON.parse(await readFile(process.env.DIANTUO_BROWSER_FIXTURE,'utf8'));
async function login(page,account=0){await page.goto('/');await page.getByLabel('账号',{exact:true}).fill(fixture.accounts[account].username);await page.getByLabel('密码',{exact:true}).fill(fixture.accounts[account].password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('button',{name:'开始仿真',exact:true})).toBeVisible();}
async function disclosure(page){const d=page.locator('.dt-document-disclosure');if(await d.getAttribute('open')===null)await d.locator('summary').click();}
async function collapse(page){const d=page.locator('.dt-document-disclosure');if(await d.getAttribute('open')!==null)await d.locator('summary').click();const button=page.getByRole('button',{name:'收起图纸',exact:true});if(await button.isVisible())await button.click();await page.locator('.react-flow__controls-fitview').click();}
async function importDocument(page,document){await disclosure(page);await page.getByRole('button',{name:'新建电路',exact:true}).click();await page.getByRole('button',{name:'导入本地保存的图纸',exact:true}).click();await page.getByLabel('待导入的电路 JSON',{exact:true}).fill(JSON.stringify(document));await page.getByRole('button',{name:'导入粘贴内容',exact:true}).click();await collapse(page);}
async function dragWire(page,a,b){const from=page.locator(`[data-terminal-key="${a}"]`),to=page.locator(`[data-terminal-key="${b}"]`);await from.hover();await to.hover();const aa=await from.boundingBox(),bb=await to.boundingBox();await page.mouse.move(aa.x+aa.width/2,aa.y+aa.height/2);await page.mouse.down();await page.mouse.move(bb.x+bb.width/2,bb.y+bb.height/2,{steps:12});await page.mouse.up();}
async function geometry(page){const w=page.locator('.sim-wire').first();const g=await w.evaluate(e=>({a:JSON.parse(e.dataset.fromWorld),b:JSON.parse(e.dataset.toWorld),from:e.dataset.fromTerminal,to:e.dataset.toTerminal,path:e.querySelector('.react-flow__edge-path').getAttribute('d')}));for(const [id,p] of [[g.from,g.a],[g.to,g.b]])expect(await page.locator(`[data-terminal-key="${id}"]`).evaluate(e=>({x:Number(e.dataset.worldX),y:Number(e.dataset.worldY)}))).toEqual(p);return g;}
async function rotatedArtworkFits(shell){
 const outer=await shell.boundingBox(),art=await shell.locator('.sim-supply-artwork').boundingBox();
 expect(art.width).toBeGreaterThan(10);expect(art.height).toBeGreaterThan(10);
 expect(Math.abs(art.width-outer.width)).toBeLessThan(2);expect(Math.abs(art.height-outer.height)).toBeLessThan(2);
 expect(Math.abs(art.x-outer.x)).toBeLessThan(2);expect(Math.abs(art.y-outer.y)).toBeLessThan(2);
}
async function screenshot(page,name){await page.screenshot({path:path.join(process.env.DIANTUO_BROWSER_PRIVATE_OUTPUT,`${name}.png`),fullPage:true});}
test('feedback 20261005: rotation, drag, undo, zoom, copy, reload and immutable publication',async({page,browser})=>{
 await login(page);const d={schemaVersion:1,title:'Browser feedback rotation',components:[{id:'source',type:'supply',label:'电源',position:{x:500,y:50},rotation:180},{id:'strip',type:'terminal-strip16',label:'XT',position:{x:80,y:350}},{id:'duct',type:'wire-duct',label:'WD',position:{x:0,y:250},size:{width:900,height:40}}],wires:[]};await importDocument(page,d);await screenshot(page,'rotation-before');await dragWire(page,'source::L1','strip::T1');await expect(page.locator('.sim-wire')).toHaveCount(1);const before=await geometry(page);
 await page.locator('[data-device-id="source"]').click({position:{x:30,y:12}});await page.getByRole('button',{name:'旋转90°',exact:true}).click();const after=await geometry(page);await rotatedArtworkFits(page.locator('[data-device-id="source"]'));expect(after.a).not.toEqual(before.a);await page.getByRole('button',{name:'撤销',exact:true}).click();expect(await geometry(page)).toEqual(before);await page.getByRole('button',{name:'重做',exact:true}).click();expect(await geometry(page)).toEqual(after);
 await page.locator('.react-flow__controls-zoomout').click();expect(await geometry(page)).toEqual(after);const node=page.locator('[data-device-id="source"]'),box=await node.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+45,box.y+box.height/2+25,{steps:15});await page.mouse.up();const moved=await geometry(page);expect(moved.a).not.toEqual(after.a);
 await page.getByRole('button',{name:'复制选中对象',exact:true}).click();await page.getByRole('button',{name:'粘贴对象',exact:true}).click();await expect(page.locator('[data-component-type="supply"]')).toHaveCount(2);await page.getByRole('button',{name:'撤销',exact:true}).click();
 const saved=page.waitForResponse(r=>r.url().endsWith('/api/circuits')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存草稿',exact:true}).click();const response=await saved;expect(response.status()).toBe(201);const original=(await response.json()).circuit;expect(original.document.components.find(c=>c.id==='source').rotation).toBe(270);
 await page.reload();await expect(page.locator('.sim-wire')).toHaveCount(1);expect(await geometry(page)).toEqual(moved);await screenshot(page,'rotation-after');
 const publish=await page.request.post(`/api/circuits/${original.id}/publish`,{headers:{origin:new URL(page.url()).origin},data:{revision:original.revision,mediaIds:[]}});expect(publish.status()).toBe(201);const publication=(await publish.json()).publication;const changed=structuredClone(original.document);changed.components[0].rotation=0;expect((await page.request.put(`/api/circuits/${original.id}`,{headers:{origin:new URL(page.url()).origin},data:{title:changed.title,document:changed,revision:original.revision,mediaIds:[]}})).status()).toBe(200);const snap=await page.request.get(`/api/publications/${publication.id}`);expect((await snap.json()).publication.document).toEqual(original.document);
 const context=await browser.newContext();try{const other=await context.newPage();await login(other,1);expect((await other.request.get(`/api/circuits/${original.id}`)).status()).toBe(404);expect((await other.request.put(`/api/circuits/${original.id}`,{headers:{origin:new URL(other.url()).origin},data:{title:changed.title,document:changed,revision:2,mediaIds:[]}})).status()).toBe(404);await other.goto('/gallery?publication='+publication.id);await expect(other.locator('.dt-gallery-detail')).toBeVisible();await rotatedArtworkFits(other.locator('.dt-gallery-detail .sim-preview-device').filter({has:other.locator('.sim-supply-artwork')}));await screenshot(other,'rotation-publication-member');}finally{await context.close();}
 await page.getByRole('link',{name:'仿真广场',exact:true}).click();await page.goto(`/gallery?publication=${publication.id}`); await expect(page.locator('.dt-gallery-detail')).toBeVisible();await rotatedArtworkFits(page.locator('.dt-gallery-detail .sim-preview-device').filter({has:page.locator('.sim-supply-artwork')}));await screenshot(page,'rotation-publication');
});
test('feedback 20261005: manual course 01 uses student IDs, actual placement and terminal drags',async({page})=>{
 test.setTimeout(150000);await login(page);await disclosure(page);const oldCount=await page.locator('[data-device-id]').count();await page.getByLabel('选择训练课程',{exact:true}).selectOption('motor-course-01');await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('[data-device-id]')).toHaveCount(oldCount);
 await page.getByLabel('选择训练课程',{exact:true}).selectOption('motor-course-01');await page.getByLabel('手动放置元件',{exact:false}).check();await page.getByRole('button',{name:'创建练习',exact:true}).click();await expect(page.locator('[data-device-id]')).toHaveCount(8);await collapse(page);await page.getByRole('button',{name:'检查接线',exact:true}).click();await expect(page.locator('.sim-assessment-status')).toContainText('课程器件未齐');await page.getByRole('button',{name:'收起检查结果',exact:true}).click();await page.getByLabel('线条样式',{exact:true}).selectOption('straight');await page.locator('.sim-course-checklist summary').click();for(let i=0;i<3;i++)await page.locator('.react-flow__controls-zoomout').click();
 const template=fixture.drafts['motor-course-01:correct'].document;
 for(const [role,id] of Object.entries(template.roles)){const c=template.components.find(c=>c.id===id);const row=page.locator('.sim-course-checklist > div').filter({has:page.getByText(c.label,{exact:true})});await row.getByRole('button',{name:'添加并放置',exact:true}).click();const position=role==='source'?{x:980,y:40}:role==='m'?{x:1000,y:350}:c.position;const point=await page.locator('.react-flow__viewport').evaluate((e,p)=>{const m=new DOMMatrix(getComputedStyle(e).transform),r=e.parentElement.getBoundingClientRect();return {x:r.x+m.e+p.x*m.a,y:r.y+m.f+p.y*m.d};},position);await page.mouse.click(point.x,point.y);await expect(row.getByRole('button',{name:'已绑定',exact:true})).toBeDisabled();}
 await page.locator('.react-flow__controls-fitview').click();const firstSave=page.waitForResponse(r=>r.url().endsWith('/api/circuits')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存草稿',exact:true}).click();const draft=(await (await firstSave).json()).circuit;expect(draft.document.roles.qf).not.toBe('qf');expect(draft.document.wires).toHaveLength(0);
 const reverse=Object.fromEntries(Object.entries(template.roles).map(([role,id])=>[id,role]));for(const [i,w] of template.wires.entries()){await dragWire(page,`${draft.document.roles[reverse[w.from.componentId]]}::${w.from.terminalId}`,`${draft.document.roles[reverse[w.to.componentId]]}::${w.to.terminalId}`);await expect(page.locator('.sim-wire')).toHaveCount(i+1);}
 await page.getByRole('button',{name:'检查接线',exact:true}).click();await expect(page.locator('.sim-assessment-status')).toContainText('课程通过');await screenshot(page,'manual-course-01');const saved=page.waitForResponse(r=>r.url().endsWith(`/api/circuits/${draft.id}`)&&r.request().method()==='PUT');await page.getByRole('button',{name:'保存草稿',exact:true}).click();expect((await saved).status()).toBe(200);await page.reload();await expect(page.locator('.sim-wire')).toHaveCount(template.wires.length);await geometry(page);
});
test('feedback 20261005: numeric KT screen, ON UP, pause step, loss and restart',async({page})=>{
 await login(page);const d={schemaVersion:1,title:'Browser feedback timer',components:[{id:'s',type:'supply',label:'电源',position:{x:0,y:0}},{id:'kt',type:'timer380-8pin',label:'KT',position:{x:350,y:120},settings:{delayMs:3000}}],wires:[{id:'one',from:{componentId:'s',terminalId:'L1'},to:{componentId:'kt',terminalId:'2'},color:'#203040'},{id:'two',from:{componentId:'s',terminalId:'L2'},to:{componentId:'kt',terminalId:'7'},color:'#203040'}]};await importDocument(page,d);const kt=page.locator('[data-device-id="kt"]');await expect(kt.locator('[data-timer-display]')).toHaveText('00:03');await page.getByRole('button',{name:'开始仿真',exact:true}).click();await page.getByRole('button',{name:'暂停计时',exact:true}).click();await expect(kt.locator('[data-timer-indicator="ON"]')).toHaveAttribute('data-lit','true');await expect(kt.locator('[data-timer-indicator="UP"]')).toHaveAttribute('data-lit','false');await page.getByRole('button',{name:'推进 1 秒',exact:true}).click();await expect(kt.locator('[data-timer-seconds]')).toHaveText(/1\.|2\./);for(let i=0;i<3;i++)await page.getByRole('button',{name:'推进 1 秒',exact:true}).click();await expect(kt.locator('[data-timer-display]')).toHaveText('00:00');await expect(kt.locator('[data-timer-indicator="UP"]')).toHaveAttribute('data-lit','true');await screenshot(page,'timer-done');await page.getByRole('button',{name:'结束仿真',exact:true}).click();await expect(kt.locator('[data-timer-indicator="ON"]')).toHaveAttribute('data-lit','false');await expect(kt.locator('[data-timer-indicator="UP"]')).toHaveAttribute('data-lit','false');await expect(kt.locator('[data-timer-display]')).toHaveText('00:03');await page.getByRole('button',{name:'开始仿真',exact:true}).click();await expect(kt).toHaveAttribute('data-runtime-state','timing');
});
test('feedback 20261005: explicit legacy upgrade creates a copy and leaves original snapshot intact',async({page})=>{
 await login(page);const d={schemaVersion:1,title:'Browser feedback legacy',components:[{id:'s',type:'supply',label:'电源',position:{x:0,y:0}},{id:'kt',type:'timer380',label:'KT',position:{x:350,y:120},settings:{delayMs:3000}}],wires:[{id:'one',from:{componentId:'s',terminalId:'L1'},to:{componentId:'kt',terminalId:'A1'},color:'#203040'},{id:'two',from:{componentId:'s',terminalId:'L2'},to:{componentId:'kt',terminalId:'A2'},color:'#203040'}]};await importDocument(page,d);const saving=page.waitForResponse(r=>r.url().endsWith('/api/circuits')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存草稿',exact:true}).click();const old=(await (await saving).json()).circuit;await disclosure(page);await page.getByRole('button',{name:'升级继电器并另存副本',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('[data-component-type="timer380"]')).toHaveCount(1);await page.getByRole('button',{name:'升级继电器并另存副本',exact:true}).click();const upgraded=page.waitForResponse(r=>r.url().endsWith('/api/circuits')&&r.request().method()==='POST');await page.getByRole('button',{name:'升级并保存副本',exact:true}).click();const copy=(await (await upgraded).json()).circuit;expect(copy.id).not.toBe(old.id);expect(copy.document.wires.map(w=>w.to.terminalId)).toEqual(['2','7']);await expect(page.locator('[data-component-type="timer380-8pin"]')).toHaveCount(1);expect((await (await page.request.get(`/api/circuits/${old.id}`)).json()).circuit.document).toEqual(old.document);
});
